### ISSUE TITLE
React

### ISSUE THREAD

**Issue by PakizeBozkurt** [PakizeBozkurt/node-users#1]
Create a react app!

**Comment by Asif032000** [comment]
I can create a react app. Also I've noticed you've pushed node_modules along with the code, which should not be done, instead you should have a .gitignore file which should have file names ( node_modules in this case ) which are to be ignored while pushing the changes.

**Comment by PakizeBozkurt** [comment]
Hi Asif032000,
Thank you so much for your notice.
I created react app. If you want to see it, just go 'React-users' repo.
Fell free to add your ideas!
